include: package:very_good_analysis/analysis_options.2.4.0.yaml
linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types: false
    flutter_style_todos: false
    sort_unnamed_constructors_first: false
    no_default_cases: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    sort_pub_dependencies: false
analyzer:
  strong-mode:
    implicit-casts: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated"
    - "analysis_options.yaml"
  errors:
    invalid_annotation_target: ignore