// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkZYI3UoNEwkuEHC-kVKOHVhA_Cxk7K0o',
    appId: '1:1082990291777:web:d053dffc8739be9cc20fc0',
    messagingSenderId: '1082990291777',
    projectId: 'howaboutnow-3ec4c',
    authDomain: 'howaboutnow-3ec4c.firebaseapp.com',
    storageBucket: 'howaboutnow-3ec4c.appspot.com',
    measurementId: 'G-CQ7EYYSFFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeSnaUjLQLSWhjPKw_3Hc-8YLm96OZK2Q',
    appId: '1:1082990291777:android:cff082b0b9cf57c9c20fc0',
    messagingSenderId: '1082990291777',
    projectId: 'howaboutnow-3ec4c',
    storageBucket: 'howaboutnow-3ec4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxzGWMXrworTXEcP3JAE_r02gw-6_l7g',
    appId: '1:1082990291777:ios:3bd11b53a03e8ce9c20fc0',
    messagingSenderId: '1082990291777',
    projectId: 'howaboutnow-3ec4c',
    storageBucket: 'howaboutnow-3ec4c.appspot.com',
    iosBundleId: 'com.example.howAboutNow',
  );
}
